apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appservices.sense12.com
spec:
  group: sense12.com
  names:
    kind: AppService
    listKind: AppServiceList
    plural: appservices
    singular: appservice
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            image:
              type: string
            ports:
              properties:
                name:
                  type: string
                port:
                  type: integer
